### ISSUE TITLE
Ex Nihilo integration

### ISSUE THREAD

**Issue by OrdinatorStouff** [The-Acronym-Coders/B.A.S.E#61]
Posting here from Discord conversation

Integration for Ore chunks/pieces/sand/gravel/dust that Nihilo uses in sieve system plus maybe other things like "pebbles" or something else

There are two different "styles" of Nihilo on 1.10 (Adsendiso and Omnia) that have components that vary slightly. For 1.12 the "Adsendiso" variant is the only one that I know of having a port being developed at this time.

I can provide a more detailed list of items/suggestions at a later time

**Comment by Lanse505** [comment]
I actually talked to Blood today about this @OrdinatorStouff 
Apparently they have/are adding their own Json-Based system for adding custom hammers, ores, recipes, etc, etc from what I understood talking to him. 

So both he and I feel there is really no need for ContentTweaker/Base Support for this mod.
Ofc is Zenscript support is really that wanted, you could always PR him to add it natively since if there exists systems for Json the you should (in theory) be able to add quite easy Zenscript support.

//Best Regards
Lanse
